// Mock subscription data for list screen development
// 10 subscriptions matching the dashboard stats (~98.26 EUR/month)

import type { Subscription } from './types';

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'ChatGPT Plus',
    logo_url: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    category: 'ai',
    price_amount: 20.00,
    currency: 'US$',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(12),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2024-11-15T10:00:00Z',
    updated_at: '2024-11-15T10:00:00Z',
    monthly_equivalent_cost: 20.00,
    my_monthly_cost: 20.00,
  },
  {
    id: '2',
    name: 'Claude Pro',
    logo_url: 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
    category: 'ai',
    price_amount: 20.00,
    currency: 'US$',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(8),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
    monthly_equivalent_cost: 20.00,
    my_monthly_cost: 20.00,
  },
  {
    id: '3',
    name: 'Notion',
    logo_url: 'https://www.google.com/s2/favicons?domain=notion.so&sz=128',
    category: 'productivity',
    price_amount: 16.00,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(3),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2024-10-20T10:00:00Z',
    updated_at: '2024-10-20T10:00:00Z',
    monthly_equivalent_cost: 16.00,
    my_monthly_cost: 16.00,
  },
  {
    id: '4',
    name: 'Spotify',
    logo_url: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=128',
    category: 'music',
    price_amount: 9.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(18),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2023-06-01T10:00:00Z',
    updated_at: '2023-06-01T10:00:00Z',
    monthly_equivalent_cost: 9.99,
    my_monthly_cost: 9.99,
  },
  {
    id: '5',
    name: 'Netflix',
    logo_url: 'https://www.google.com/s2/favicons?domain=netflix.com&sz=128',
    category: 'streaming',
    price_amount: 6.00,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(5),
    status: 'active',
    is_shared: true,
    shared_with_count: 3,
    card_color: null,
    created_at: '2023-01-15T10:00:00Z',
    updated_at: '2023-01-15T10:00:00Z',
    monthly_equivalent_cost: 17.99,
    my_monthly_cost: 6.00,
  },
  {
    id: '6',
    name: 'YouTube Premium',
    logo_url: 'https://www.google.com/s2/favicons?domain=youtube.com&sz=128',
    category: 'streaming',
    price_amount: 6.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(22),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
    monthly_equivalent_cost: 6.99,
    my_monthly_cost: 6.99,
  },
  {
    id: '7',
    name: 'GitHub',
    logo_url: 'https://www.google.com/s2/favicons?domain=github.com&sz=128',
    category: 'cloud',
    price_amount: 4.00,
    currency: 'US$',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(1),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2023-09-01T10:00:00Z',
    updated_at: '2023-09-01T10:00:00Z',
    monthly_equivalent_cost: 4.00,
    my_monthly_cost: 4.00,
  },
  {
    id: '8',
    name: 'iCloud+',
    logo_url: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128',
    category: 'cloud',
    price_amount: 2.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(14),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2022-08-01T10:00:00Z',
    updated_at: '2022-08-01T10:00:00Z',
    monthly_equivalent_cost: 2.99,
    my_monthly_cost: 2.99,
  },
  {
    id: '9',
    name: 'Figma',
    logo_url: 'https://www.google.com/s2/favicons?domain=figma.com&sz=128',
    category: 'productivity',
    price_amount: 8.00,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(25),
    status: 'active',
    is_shared: true,
    shared_with_count: 2,
    card_color: null,
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-01-01T10:00:00Z',
    monthly_equivalent_cost: 16.00,
    my_monthly_cost: 8.00,
  },
  {
    id: '10',
    name: 'Disney+',
    logo_url: 'https://www.google.com/s2/favicons?domain=disneyplus.com&sz=128',
    category: 'streaming',
    price_amount: 4.29,
    currency: 'EUR',
    billing_period: 'yearly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(87),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
    created_at: '2024-05-20T10:00:00Z',
    updated_at: '2024-05-20T10:00:00Z',
    monthly_equivalent_cost: 4.29,
    my_monthly_cost: 4.29,
  },
];
