import { logoUrlFromDomain } from './constants/platforms';
import type { Subscription } from '../features/subscriptions/types';

const REVIEW_EMAILS = [
  'carlosparienteparientecarlos@gmail.com',
];

export function isReviewAccount(email: string | undefined | null): boolean {
  if (!email) return false;
  return REVIEW_EMAILS.includes(email.toLowerCase().trim());
}

type SeedSub = Omit<
  Subscription,
  'id' | 'created_at' | 'updated_at' | 'monthly_equivalent_cost' | 'my_monthly_cost'
>;

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const REVIEW_SEED_SUBSCRIPTIONS: SeedSub[] = [
  {
    name: 'Netflix',
    logo_url: logoUrlFromDomain('netflix.com'),
    category: 'streaming',
    price_amount: 12.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(5),
    status: 'active',
    is_shared: true,
    shared_with_count: 3,
    card_color: '#E50914',
  },
  {
    name: 'Spotify Premium',
    logo_url: logoUrlFromDomain('spotify.com'),
    category: 'music',
    price_amount: 10.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(12),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#1DB954',
  },
  {
    name: 'iCloud+',
    logo_url: logoUrlFromDomain('icloud.com'),
    category: 'cloud',
    price_amount: 2.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(18),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
  },
  {
    name: 'ChatGPT Plus',
    logo_url: logoUrlFromDomain('openai.com'),
    category: 'ai',
    price_amount: 20.00,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(9),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#412991',
  },
  {
    name: 'YouTube Premium',
    logo_url: logoUrlFromDomain('youtube.com'),
    category: 'streaming',
    price_amount: 13.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(22),
    status: 'active',
    is_shared: true,
    shared_with_count: 5,
    card_color: '#FF0000',
  },
  {
    name: 'Notion',
    logo_url: logoUrlFromDomain('notion.so'),
    category: 'productivity',
    price_amount: 96.00,
    currency: 'EUR',
    billing_period: 'yearly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(74),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: null,
  },
  {
    name: 'Disney+',
    logo_url: logoUrlFromDomain('disneyplus.com'),
    category: 'streaming',
    price_amount: 8.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(15),
    status: 'active',
    is_shared: true,
    shared_with_count: 2,
    card_color: '#113CCF',
  },
  {
    name: 'Figma',
    logo_url: logoUrlFromDomain('figma.com'),
    category: 'productivity',
    price_amount: 144.00,
    currency: 'EUR',
    billing_period: 'yearly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(130),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#F24E1E',
  },
  {
    name: 'NordVPN',
    logo_url: logoUrlFromDomain('nordvpn.com'),
    category: 'other',
    price_amount: 59.88,
    currency: 'EUR',
    billing_period: 'yearly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(200),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#4687FF',
  },
  {
    name: 'Duolingo',
    logo_url: logoUrlFromDomain('duolingo.com'),
    category: 'education',
    price_amount: 6.99,
    currency: 'EUR',
    billing_period: 'monthly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(25),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#58CC02',
  },
  {
    name: 'Amazon Prime',
    logo_url: logoUrlFromDomain('amazon.com'),
    category: 'other',
    price_amount: 49.90,
    currency: 'EUR',
    billing_period: 'yearly',
    billing_interval_count: 1,
    next_billing_date: daysFromNow(60),
    status: 'active',
    is_shared: false,
    shared_with_count: 0,
    card_color: '#FF9900',
  },
];
